services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '25MB'
    ulimits:
      nofile:
        soft: 100000
        hard: 100000

  redis:
    image: redis:alpine
    networks:
      - backend
      - payment-processor
    command: redis-server --maxmemory 35mb --maxmemory-policy allkeys-lru --save ""
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'
    restart: unless-stopped

  healthchecker:
    build:
      context: ./healthchecker
      dockerfile: Dockerfile
    networks:
      - payment-processor
      - backend
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - CHECK_INTERVAL=5
      - MIN_RESPONSE_TIME_LIMIT_MS=100
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '25MB'
    restart: unless-stopped
    depends_on:
      - redis

  backend-1: &backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "115MB"
    restart: unless-stopped
    depends_on:
      - redis
      - healthchecker

  backend-2:
    <<: *backend-1

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true 
