version: "2.4"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      backend-1:
        condition: service_healthy
      backend-2: 
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25' # Não mexer aqui
          memory: '20MB' # Não mexer aqui
    ulimits:
      nofile:
        soft: 100000
        hard: 100000

  backend-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.625"
          memory: "165MB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-2:9999/health"]
      start_period: 10s
      timeout: 1s
      interval: 10m
      retries: 3

  backend-2: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.625"
          memory: "165MB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-2:9999/health"]
      start_period: 10s
      timeout: 1s
      interval: 10m
      retries: 3

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true 
